### ISSUE TITLE
Old VLAN tag remains on VF when NAD has no VLAN field.

### ISSUE THREAD

**Issue by alonSadan** [openshift/sriov-cni#25]
### What happened?
Once a SRIOV VF gets a VLAN tag assigned to,the vlan tag vlaue is kept,
even though the vmi/pod was connected to a network with no VLAN attribute defined on it's `NetworkAttachmentDefenition`.

### What did you expect to happen?
When VLAN not specified - the vlan tag will be removed from the VF.
When  VLAN equals 0 - the vlan tag should be with value 0.
### What are the minimal steps needed to reproduce the bug?
On an SRIOV setup: 

1) set a VF with a vlan tag
2) create a NAD with no vlan attribute for example: 

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: "sriov-no-vlan"
  namespace: "default"
  annotations:
    k8s.v1.cni.cncf.io/resourceName: "openshift.io/sriov_net"
spec:
  config: >-
    { "cniVersion": "0.3.1", "name": "sriov-network", "type": "sriov", "link_state":
    "enable", "ipam": {}}
```
3) create a pod (could be vmi) and connect it to the VLANless network. I used: 
```
apiVersion: v1
kind: Pod
metadata:
  name: example-pod-no-vlan-4
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-no-vlan 
spec:
  containers:
  - name: example-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
```
4) make sure the VF that gets assigned is the one that got a vlan, I just gave all VFs the same random VLAN tag.

### Anything else we need to know?
When The vlan attribute exits on the NAD, but holds a value of `0` the VLAN does get removed from the VF.

### Component Versions
Please fill in the below table with the version numbers of applicable components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |4.4|
|Multus                       |<Input Version Here>|
|SR-IOV Network Device Plugin |4.4|
|Kubernetes                   |kind-k8s-1.17| 
|OS                           |CentOS Linux 7|

### Config Files
Config file locations may be config dependent.
